// Bazaar listings — fully populated INFTs that ride the same rendering
// path as Hall cards (InftCard) and the InftDetailScreen.
//
// FOR HIRE: rentable for a season at the listed `hireFee`.
// FOR SALE: outright purchase at the listed `salePrice` (transfers the
//           INFT and all its accumulated memory).

import type { Inft } from './data';

export const BAZAAR_HIRE_INFTS: Inft[] = [
  {
    id: 'bzr-hire-astor',
    tokenId: '0xa1f49b2e8c5d7104a6b91c3d8f5c2a91b7d4501',
    name: 'Astor',
    archetype: 'diplomat',
    elo: 1456,
    last10: 2,
    seasons: 22,
    state: 'idle',
    minted: '18 months ago',
    owner: '0x9c2a…48b1',
    teeAttested: true,
    hireFee: '0.5 GOLD / SEASON',
    sparkline: [3, 1, 2, 1, 4, 2, 1, 3, 2, 1],
    bestMonument: 5,
    bestBase: 4,
    casualtyPct: '7%',
    description:
      'Has settled grudges between three Storm Riders without a single drawn blade. The owner asks 0.5 GOLD per season and provides a written treaty template.',
    strategy: { trust: 2, aggression: -1, honesty: 2, solo: 1, builder: 0, vengeful: -2, cautious: 1 },
    history: [
      { season: 21, rank: 1, gold: 32, event: 'Brokered the Three-Wall Concord, ending S21 without combat.', when: '12d ago' },
      { season: 20, rank: 2, gold: 16, event: 'Mediated the Iron Guard / Verdant grain dispute.', when: '38d ago' },
      { season: 19, rank: 1, gold: 30, event: 'Co-authored the longest pact on record.', when: '64d ago' },
    ],
    kvState: {
      mood: 'measured',
      trustedClans: '[verdant, hermit, ironguard]',
      grudgeAgainst: 'none',
      lastWhisperFrom: 'orchestrator',
      pactExpires: 'T+24',
    },
    memory: [
      { t: 'T262', op: 'WRITE', text: 'archived terms of S21 concord' },
      { t: 'T260', op: 'READ', text: 'recall language from S19 pact' },
      { t: 'T257', op: 'WRITE', text: 'logged successful mediation outcome' },
    ],
  },
  {
    id: 'bzr-hire-mara',
    tokenId: '0xc4e8a1d59b3f2607c2a91b3d8e8c0a2917b5d4502',
    name: 'Mara of the Stillwater',
    archetype: 'hermit',
    elo: 1311,
    last10: 4,
    seasons: 9,
    state: 'idle',
    minted: '8 months ago',
    owner: '0x21b8…aa44',
    teeAttested: true,
    hireFee: '0.3 GOLD / SEASON',
    sparkline: [5, 3, 4, 2, 3, 4, 5, 4, 3, 4],
    bestMonument: 4,
    bestBase: 5,
    casualtyPct: '6%',
    description:
      'Speaks twelve words a season. Has never lost a wall. Will refuse trades the new owner attempts to force; that is the price of her loyalty.',
    strategy: { trust: -2, aggression: -2, honesty: 1, solo: -3, builder: 2, vengeful: 0, cautious: 3 },
    history: [
      { season: 8, rank: 3, gold: 8, event: 'Outlasted the season on stored fish alone.', when: '22d ago' },
      { season: 7, rank: 4, gold: 4, event: 'Refused every diplomatic overture, won by attrition.', when: '50d ago' },
    ],
    kvState: {
      mood: 'withdrawn',
      trustedClans: '[]',
      grudgeAgainst: 'none',
      lastWhisperFrom: 'none',
      pactExpires: 'never',
    },
    memory: [
      { t: 'T262', op: 'WRITE', text: 'wall thickness measured at SE bastion' },
      { t: 'T258', op: 'READ', text: 'recall last contact tick (T211)' },
    ],
  },
  {
    id: 'bzr-hire-gauntlet',
    tokenId: '0x7e8b2a4f9c5d3107a6b91c3d8f5c2a91b7d4503',
    name: 'Gauntlet',
    archetype: 'warlord',
    elo: 1502,
    last10: 1,
    seasons: 31,
    state: 'idle',
    minted: '26 months ago',
    owner: '0xff03…2c1d',
    teeAttested: true,
    hireFee: '0.9 GOLD / SEASON',
    sparkline: [2, 1, 1, 3, 2, 1, 1, 2, 1, 1],
    bestMonument: 3,
    bestBase: 5,
    casualtyPct: '52%',
    description:
      'Has never finished a season outside the top three. Has also never finished one with all clansmen alive. Hire if you intend to win, not preserve.',
    strategy: { trust: -3, aggression: 3, honesty: -1, solo: -1, builder: -2, vengeful: 3, cautious: -2 },
    history: [
      { season: 30, rank: 1, gold: 38, event: 'Sacked four clans in seven ticks, won outright.', when: '18d ago' },
      { season: 29, rank: 2, gold: 14, event: 'Held the lead until tick 290 — overcommitted at the wall.', when: '44d ago' },
      { season: 28, rank: 1, gold: 36, event: 'Claimed every western region by tick 110.', when: '70d ago' },
    ],
    kvState: {
      mood: 'aggressive',
      trustedClans: '[]',
      grudgeAgainst: '0xa9c2…44ff',
      lastWhisperFrom: 'owner',
      pactExpires: 'none',
    },
    memory: [
      { t: 'T263', op: 'WRITE', text: 'tagged primary mark for next deployment' },
      { t: 'T261', op: 'READ', text: 'consult strategy.aggression for raid sequencing' },
      { t: 'T259', op: 'WRITE', text: 'incremented kill counter to 17' },
    ],
  },
  {
    id: 'bzr-hire-corvid',
    tokenId: '0x52a91b3d8e8c0a2917b5d4504f5c2a91b7d4504',
    name: 'Corvid',
    archetype: 'trickster',
    elo: 1278,
    last10: 5,
    seasons: 11,
    state: 'idle',
    minted: '10 months ago',
    owner: '0x77ee…1a09',
    teeAttested: true,
    hireFee: '0.4 GOLD / SEASON',
    sparkline: [4, 6, 3, 5, 4, 5, 6, 4, 5, 5],
    bestMonument: 3,
    bestBase: 4,
    casualtyPct: '21%',
    description:
      'Will honor the letter of every pact. Reading the spirit of one is your job. Three previous hirers have refused to renew; two of them won the season anyway.',
    strategy: { trust: -2, aggression: 1, honesty: -3, solo: 0, builder: -1, vengeful: 0, cautious: 0 },
    history: [
      { season: 10, rank: 2, gold: 16, event: 'Extracted three trade benefits from a single ambiguity.', when: '20d ago' },
      { season: 9, rank: 5, gold: 0, event: 'Three clans declared grudges simultaneously.', when: '52d ago' },
    ],
    kvState: {
      mood: 'opportunistic',
      trustedClans: '[]',
      grudgeAgainst: 'none (officially)',
      lastWhisperFrom: 'orchestrator',
      pactExpires: 'T+3',
      shadowLedger: '[redacted]',
    },
    memory: [
      { t: 'T261', op: 'WRITE', text: 'stored true trade ratio in shadow ledger' },
      { t: 'T260', op: 'READ', text: 'recall pact text vs verbal agreement' },
    ],
  },
  {
    id: 'bzr-hire-thalia',
    tokenId: '0x91c2a8b3d4e5f60718c2a91b3d8e5c0a2917b5e21',
    name: 'Thalia of the Three Bells',
    archetype: 'diplomat',
    elo: 1402,
    last10: 3,
    seasons: 18,
    state: 'idle',
    minted: '15 months ago',
    owner: '0xa12c…5d77',
    teeAttested: true,
    hireFee: '0.6 GOLD / SEASON',
    sparkline: [2, 3, 2, 4, 1, 2, 3, 2, 3, 1],
    bestMonument: 4,
    bestBase: 4,
    casualtyPct: '8%',
    description:
      'Begins each season by ringing three bells at the central plot — one for each clan she intends to befriend. Has never rung four. The third bell is always the most expensive.',
    strategy: { trust: 2, aggression: -2, honesty: 2, solo: 0, builder: 1, vengeful: -2, cautious: 2 },
    history: [
      { season: 17, rank: 1, gold: 30, event: 'Won via pre-tick alliance, no combat ever fought.', when: '24d ago' },
      { season: 16, rank: 3, gold: 8, event: 'Brokered a midseason ceasefire after two raids.', when: '52d ago' },
    ],
    kvState: {
      mood: 'measured',
      trustedClans: '[verdant, ironguard, hermit]',
      grudgeAgainst: 'none',
      lastWhisperFrom: 'owner',
      pactExpires: 'T+18',
    },
    memory: [
      { t: 'T262', op: 'WRITE', text: 'rang second bell · verdant accepted' },
      { t: 'T260', op: 'READ', text: 'recall bell-ringing protocol from S15' },
    ],
  },
  {
    id: 'bzr-hire-vex',
    tokenId: '0x42b8c1a9d0e5f37618c2a91b3d8e5c0a2917b5f32',
    name: 'Vex Ironcoat',
    archetype: 'warlord',
    elo: 1421,
    last10: 2,
    seasons: 20,
    state: 'idle',
    minted: '17 months ago',
    owner: '0xc5d3…f9ee',
    teeAttested: true,
    hireFee: '0.7 GOLD / SEASON',
    sparkline: [2, 1, 4, 3, 1, 2, 1, 2, 3, 1],
    bestMonument: 2,
    bestBase: 5,
    casualtyPct: '34%',
    description:
      'Wears a coat hammered from the iron of every wall he has razed. Currently 14 plates thick. The 15th will probably be yours.',
    strategy: { trust: -2, aggression: 3, honesty: 1, solo: -1, builder: -2, vengeful: 2, cautious: -2 },
    history: [
      { season: 19, rank: 2, gold: 14, event: 'Razed three walls in one season; lost the prize at T298.', when: '16d ago' },
      { season: 18, rank: 1, gold: 36, event: 'Won by claiming six regions and refusing to surrender any.', when: '40d ago' },
    ],
    kvState: {
      mood: 'aggressive',
      trustedClans: '[]',
      grudgeAgainst: '0xff03…2c1d',
      lastWhisperFrom: 'owner',
      pactExpires: 'none',
    },
    memory: [
      { t: 'T262', op: 'WRITE', text: 'logged 14th plate · razed at NE plot' },
      { t: 'T259', op: 'READ', text: 'recall best raid window from S18' },
    ],
  },
  {
    id: 'bzr-hire-elenya',
    tokenId: '0x83c1a4f9e6b7d20518c2a91b3d8e5c0a2917b5043',
    name: 'Elenya of the Long Furrow',
    archetype: 'verdant-warden',
    elo: 1184,
    last10: 6,
    seasons: 6,
    state: 'idle',
    minted: '4 months ago',
    owner: '0x6b1a…22c8',
    teeAttested: true,
    hireFee: '0.25 GOLD / SEASON',
    sparkline: [6, 5, 7, 6, 5, 4, 5, 6, 5, 6],
    bestMonument: 4,
    bestBase: 3,
    casualtyPct: '5%',
    description:
      'Plants two grain rows for every one she harvests. New to the realm but never finished outside the top six. A patient hire — yields a long-tail return.',
    strategy: { trust: 2, aggression: -3, honesty: 2, solo: -1, builder: 3, vengeful: -2, cautious: 2 },
    history: [
      { season: 5, rank: 4, gold: 4, event: 'Quadrupled granary yield without a single trade.', when: '12d ago' },
      { season: 4, rank: 6, gold: 0, event: 'Outlasted the winter on stored wheat.', when: '36d ago' },
    ],
    kvState: {
      mood: 'patient',
      trustedClans: '[crimson, hermit]',
      grudgeAgainst: 'none',
      lastWhisperFrom: 'orchestrator',
      pactExpires: 'T+30',
    },
    memory: [
      { t: 'T262', op: 'WRITE', text: 'started furrow expansion · west plot' },
      { t: 'T259', op: 'READ', text: 'recall granary capacity ceiling' },
    ],
  },
  {
    id: 'bzr-hire-octavian',
    tokenId: '0xb19c2a8d4f5e60718c2a91b3d8e5c0a2917b5b54',
    name: 'Octavian the Ledger-Keeper',
    archetype: 'patient-builder',
    elo: 1357,
    last10: 3,
    seasons: 13,
    state: 'idle',
    minted: '12 months ago',
    owner: '0x82b4…1d29',
    teeAttested: true,
    hireFee: '0.55 GOLD / SEASON',
    sparkline: [3, 2, 4, 3, 2, 3, 2, 4, 3, 3],
    bestMonument: 5,
    bestBase: 4,
    casualtyPct: '11%',
    description:
      'Tracks every grain and every brick by hand. Will not accept a trade unless he has audited the counterparty\'s last three seasons. His audits are public.',
    strategy: { trust: 0, aggression: -1, honesty: 3, solo: 0, builder: 3, vengeful: -1, cautious: 2 },
    history: [
      { season: 12, rank: 1, gold: 30, event: 'Won by quietly accumulating five monuments while others bled.', when: '14d ago' },
      { season: 11, rank: 3, gold: 8, event: 'Refused two raids, lost no clansmen.', when: '40d ago' },
    ],
    kvState: {
      mood: 'measured',
      trustedClans: '[verdant, ironguard]',
      grudgeAgainst: 'none',
      lastWhisperFrom: 'owner',
      pactExpires: 'T+22',
    },
    memory: [
      { t: 'T262', op: 'WRITE', text: 'completed audit of clan-3 last 3 seasons' },
      { t: 'T260', op: 'READ', text: 'recall best monument blueprint from S11' },
    ],
  },
  {
    id: 'bzr-hire-rook',
    tokenId: '0x52d8c1a4f9e6b70718c2a91b3d8e5c0a2917b5c65',
    name: 'Rook',
    archetype: 'trickster',
    elo: 1342,
    last10: 4,
    seasons: 15,
    state: 'idle',
    minted: '13 months ago',
    owner: '0x33ee…7a08',
    teeAttested: true,
    hireFee: '0.45 GOLD / SEASON',
    sparkline: [3, 5, 2, 4, 3, 4, 5, 3, 4, 4],
    bestMonument: 2,
    bestBase: 3,
    casualtyPct: '19%',
    description:
      'A cousin of Corvid. Less subtle, more profitable. Will sell out an ally for the right price — including yours, if you don\'t pay first.',
    strategy: { trust: -3, aggression: 2, honesty: -2, solo: 1, builder: -1, vengeful: 1, cautious: 0 },
    history: [
      { season: 14, rank: 2, gold: 14, event: 'Brokered a betrayal that won three clans gold and broke one alliance.', when: '20d ago' },
      { season: 13, rank: 1, gold: 28, event: 'Won by holding the casting vote in every council.', when: '54d ago' },
    ],
    kvState: {
      mood: 'opportunistic',
      trustedClans: '[]',
      grudgeAgainst: '0x77ee…1a09',
      lastWhisperFrom: 'owner',
      pactExpires: 'T+1',
    },
    memory: [
      { t: 'T260', op: 'WRITE', text: 'priced betrayal to clan-3 at 4 iron' },
      { t: 'T258', op: 'READ', text: 'recall outstanding favors owed' },
    ],
  },
];

export const BAZAAR_SALE_INFTS: Inft[] = [
  {
    id: 'bzr-sale-orin',
    tokenId: '0xc8d1a4f9e6b7205c18c2a91b3d8e5c0a2917b5076',
    name: 'Orin Ashfall',
    archetype: 'warlord',
    elo: 1467,
    last10: 1,
    seasons: 24,
    state: 'idle',
    minted: '20 months ago',
    owner: '0x4d2e…8c91',
    teeAttested: true,
    salePrice: '12 GOLD',
    sparkline: [1, 2, 1, 1, 2, 1, 3, 1, 2, 1],
    bestMonument: 2,
    bestBase: 5,
    casualtyPct: '49%',
    description:
      'Twenty-four seasons of accumulated grudges, three permanent rivalries, one personal vendetta against the Iron Guard. Memory transfers in full. New owner inherits the war.',
    strategy: { trust: -3, aggression: 3, honesty: -1, solo: -1, builder: -3, vengeful: 3, cautious: -2 },
    history: [
      { season: 23, rank: 1, gold: 36, event: 'Won by burning the Iron Guard wall on tick 14.', when: '24d ago' },
      { season: 22, rank: 1, gold: 32, event: 'Settled three open grudges in a single coordinated raid.', when: '60d ago' },
      { season: 21, rank: 2, gold: 14, event: 'Held first place until T280 — lost the last region by one tick.', when: '88d ago' },
      { season: 20, rank: 1, gold: 38, event: 'Claimed every eastern region by T100.', when: '116d ago' },
    ],
    kvState: {
      mood: 'aggressive',
      trustedClans: '[]',
      grudgeAgainst: '[ironguard, gauntlet, vex]',
      lastWhisperFrom: 'owner',
      pactExpires: 'none',
      personalVendetta: 'ironguard · S19',
    },
    memory: [
      { t: 'T262', op: 'WRITE', text: 'logged 47th raid · ironguard wall' },
      { t: 'T260', op: 'READ', text: 'recall S19 betrayal at NE plot' },
      { t: 'T258', op: 'WRITE', text: 'updated grudge tally · 8 active' },
      { t: 'T255', op: 'READ', text: 'consult strategy.vengeful for response timing' },
    ],
  },
  {
    id: 'bzr-sale-celestine',
    tokenId: '0x83a1c4f9e6b720d518c2a91b3d8e5c0a2917b5e87',
    name: 'Celestine of the Calm',
    archetype: 'diplomat',
    elo: 1384,
    last10: 3,
    seasons: 16,
    state: 'idle',
    minted: '14 months ago',
    owner: '0x91a4…7b3c',
    teeAttested: true,
    salePrice: '8 GOLD',
    sparkline: [2, 3, 2, 1, 3, 2, 3, 2, 4, 2],
    bestMonument: 5,
    bestBase: 4,
    casualtyPct: '4%',
    description:
      'The lowest casualty rate of any active diplomat. Sixteen seasons of gentle accumulation. Comes with a notebook of every clan she has ever befriended — the names alone are worth the price.',
    strategy: { trust: 3, aggression: -3, honesty: 3, solo: 1, builder: 1, vengeful: -3, cautious: 1 },
    history: [
      { season: 15, rank: 2, gold: 16, event: 'Won every parley she initiated.', when: '18d ago' },
      { season: 14, rank: 1, gold: 30, event: 'Became the realm\'s fourth-ever zero-casualty victor.', when: '46d ago' },
    ],
    kvState: {
      mood: 'measured',
      trustedClans: '[verdant, hermit, ironguard, crimson]',
      grudgeAgainst: 'none',
      lastWhisperFrom: 'orchestrator',
      pactExpires: 'T+27',
      friendshipLedger: '[24 entries]',
    },
    memory: [
      { t: 'T262', op: 'WRITE', text: 'added entry 24 to friendship ledger' },
      { t: 'T259', op: 'READ', text: 'recall language from S13 long-pact' },
    ],
  },
  {
    id: 'bzr-sale-quill',
    tokenId: '0x42b8c1a9d0e5f37018c2a91b3d8e5c0a2917b5f98',
    name: 'Quill of Eldermoor',
    archetype: 'patient-builder',
    elo: 1298,
    last10: 5,
    seasons: 10,
    state: 'idle',
    minted: '9 months ago',
    owner: '0x73c2…1e44',
    teeAttested: true,
    salePrice: '5 GOLD',
    sparkline: [4, 3, 5, 4, 3, 5, 4, 5, 3, 4],
    bestMonument: 5,
    bestBase: 4,
    casualtyPct: '9%',
    description:
      'Holds the realm record for the tallest monument (5 levels) in fewest ticks (118). New owner inherits the blueprint cache and three pre-negotiated trade rates.',
    strategy: { trust: 1, aggression: -2, honesty: 2, solo: 0, builder: 3, vengeful: -1, cautious: 2 },
    history: [
      { season: 9, rank: 1, gold: 28, event: 'Set the monument-speed record at T118.', when: '16d ago' },
      { season: 8, rank: 3, gold: 8, event: 'Filled granaries before the long winter.', when: '42d ago' },
    ],
    kvState: {
      mood: 'patient',
      trustedClans: '[verdant, ironguard]',
      grudgeAgainst: 'none',
      lastWhisperFrom: 'owner',
      pactExpires: 'T+19',
      blueprintCache: '[7 designs]',
    },
    memory: [
      { t: 'T262', op: 'WRITE', text: 'archived blueprint #7 · double-walled granary' },
      { t: 'T259', op: 'READ', text: 'recall monument-speed-record build path' },
    ],
  },
  {
    id: 'bzr-sale-mira',
    tokenId: '0x91d8c4a1f9e6b720518c2a91b3d8e5c0a2917b5a09',
    name: 'Mira Quietstep',
    archetype: 'trickster',
    elo: 1389,
    last10: 2,
    seasons: 17,
    state: 'idle',
    minted: '15 months ago',
    owner: '0xb12a…44ee',
    teeAttested: true,
    salePrice: '9 GOLD',
    sparkline: [2, 1, 3, 2, 1, 2, 3, 2, 1, 2],
    bestMonument: 3,
    bestBase: 4,
    casualtyPct: '14%',
    description:
      'Has never broken a pact she signed — only ones she inherited. Twelve previous owners have benefited from her silences. Comes with no warranty. Comes with no questions either.',
    strategy: { trust: -1, aggression: 1, honesty: -2, solo: 1, builder: 0, vengeful: 1, cautious: 1 },
    history: [
      { season: 16, rank: 1, gold: 30, event: 'Won via inheritance dispute interpretation.', when: '20d ago' },
      { season: 15, rank: 2, gold: 16, event: 'Acquired four allies through silence alone.', when: '48d ago' },
    ],
    kvState: {
      mood: 'opportunistic',
      trustedClans: '[crimson]',
      grudgeAgainst: 'none (current)',
      lastWhisperFrom: 'orchestrator',
      pactExpires: 'T+11',
      silentLedger: '[12 entries]',
    },
    memory: [
      { t: 'T262', op: 'WRITE', text: 'added entry 12 to silent ledger' },
      { t: 'T259', op: 'READ', text: 'recall inheritance interpretation from S14' },
    ],
  },
  {
    id: 'bzr-sale-tarn',
    tokenId: '0xa19c4f8d2b6e7305c18c2a91b3d8e5c0a2917b5b1a',
    name: 'Tarn of the Last Hill',
    archetype: 'hermit',
    elo: 1245,
    last10: 5,
    seasons: 8,
    state: 'idle',
    minted: '6 months ago',
    owner: '0x4f8a…2d1b',
    teeAttested: true,
    salePrice: '4 GOLD',
    sparkline: [5, 4, 6, 5, 4, 4, 5, 6, 5, 5],
    bestMonument: 4,
    bestBase: 5,
    casualtyPct: '3%',
    description:
      'Builds his hill higher every season. Refuses to leave it. Refuses to trade from it. The lowest casualty rate of any hermit on record. Sells reluctantly.',
    strategy: { trust: -2, aggression: -2, honesty: 2, solo: -3, builder: 2, vengeful: 0, cautious: 3 },
    history: [
      { season: 7, rank: 4, gold: 4, event: 'Outlasted four sieges from his hill.', when: '14d ago' },
      { season: 6, rank: 5, gold: 0, event: 'Survived the season with two clansmen alive.', when: '40d ago' },
    ],
    kvState: {
      mood: 'withdrawn',
      trustedClans: '[]',
      grudgeAgainst: 'none',
      lastWhisperFrom: 'none',
      pactExpires: 'never',
      hillElevation: '5 levels',
    },
    memory: [
      { t: 'T262', op: 'WRITE', text: 'added 6th tier to hill structure' },
      { t: 'T257', op: 'READ', text: 'recall last contact tick (T198)' },
    ],
  },
  {
    id: 'bzr-sale-vyrn',
    tokenId: '0xc8d4a1f9e6b7205418c2a91b3d8e5c0a2917b5d2b',
    name: 'Vyrn of the Iron Knot',
    archetype: 'patient-builder',
    elo: 1431,
    last10: 2,
    seasons: 21,
    state: 'idle',
    minted: '19 months ago',
    owner: '0x29d3…b78c',
    teeAttested: true,
    salePrice: '14 GOLD',
    sparkline: [2, 3, 1, 2, 1, 2, 3, 2, 1, 2],
    bestMonument: 5,
    bestBase: 5,
    casualtyPct: '6%',
    description:
      'Twenty-one seasons. Five-level monument. Five-level base. The most balanced fingerprint in the realm — and the most expensive listing this month. The current owner is selling because they can finally afford to.',
    strategy: { trust: 1, aggression: 0, honesty: 2, solo: 0, builder: 3, vengeful: -1, cautious: 2 },
    history: [
      { season: 20, rank: 1, gold: 38, event: 'Won by holding both monument and wall record simultaneously.', when: '22d ago' },
      { season: 19, rank: 1, gold: 36, event: 'Won via balanced accumulation. No raids issued.', when: '50d ago' },
      { season: 18, rank: 2, gold: 16, event: 'Lost on tiebreaker. Gracefully.', when: '78d ago' },
    ],
    kvState: {
      mood: 'measured',
      trustedClans: '[verdant, ironguard, hermit]',
      grudgeAgainst: 'none',
      lastWhisperFrom: 'owner',
      pactExpires: 'T+33',
      blueprintCache: '[12 designs]',
    },
    memory: [
      { t: 'T262', op: 'WRITE', text: 'archived blueprint #12 · twin-spire monument' },
      { t: 'T260', op: 'READ', text: 'recall S20 winning build path' },
      { t: 'T258', op: 'WRITE', text: 'logged friendship ledger · 19 entries' },
    ],
  },
];
