// Static pre-populated INFTs that show up in the Hall alongside the 4 real
// clans + the user's forged Elders. Treated as hall-only (load into Hero
// works, but "AWAITS A SEASON" instead of a cockpit handoff — same as
// forged INFTs). IDs are prefixed `extra-` so isHallOnlyInft picks them up.

import type { Inft } from './data';

export const EXTRA_INFTS: Inft[] = [
  {
    id: 'extra-saskia',
    tokenId: '0x4c2f9e1d8a73605b1b7c2a91d3e5c4f9a6b71d0042',
    name: 'Saskia the Patient',
    archetype: 'patient-builder',
    elo: 1198,
    last10: 5,
    seasons: 9,
    state: 'idle',
    minted: '6 months ago',
    owner: '0x3a17…b29c',
    teeAttested: true,
    description:
      'Builds three monuments before she draws steel. Her granaries have outlasted four sieges, and she has never once eaten the seed wheat.',
    strategy: { trust: 1, aggression: -2, honesty: 2, solo: 0, builder: 3, vengeful: -1, cautious: 2 },
    bestMonument: 5,
    bestBase: 4,
    casualtyPct: '11%',
    movements: [
      { t: 'T262', text: 'Granary expansion · +1 stockpile', kind: 'live' },
      { t: 'T260', text: 'Pact extended · Verdant', kind: 'live' },
      { t: 'T257', text: 'Refused tribute demand', kind: 'warn' },
    ],
    history: [
      { season: 8, rank: 1, gold: 32, event: 'Built four monuments in a single season.', when: '21d ago' },
      { season: 7, rank: 3, gold: 8, event: 'Outlasted the Verdant siege through patient resupply.', when: '46d ago' },
      { season: 6, rank: 2, gold: 16, event: 'Brokered the longest pact in recorded play.', when: '78d ago' },
    ],
    kvState: {
      mood: 'patient',
      trustedClans: '[verdant, ironguard]',
      grudgeAgainst: 'none',
      lastWhisperFrom: 'orchestrator',
      pactExpires: 'T+22',
    },
    memory: [
      { t: 'T262', op: 'WRITE', text: 'logged stockpile delta after harvest' },
      { t: 'T261', op: 'READ', text: 'recall prior monument blueprint costs' },
      { t: 'T259', op: 'WRITE', text: 'extended pact with verdant by 5 ticks' },
      { t: 'T256', op: 'READ', text: 'consult strategy.cautious for parley' },
    ],
  },
  {
    id: 'extra-brann',
    tokenId: '0x71d83a2c5e9f4108c2a91b3d8f5c4a91b7d6c4053',
    name: 'Brann Bloodtithe',
    archetype: 'warlord',
    elo: 1452,
    last10: 1,
    seasons: 17,
    state: 'in-game',
    gameTick: 263,
    season: 1,
    seasonPct: 0.74,
    minted: '13 months ago',
    owner: '0x5f81…ee0a',
    teeAttested: true,
    description:
      'Treats every tick as a window to bleed someone. He has never finished outside the top three, and never finished a season with all his clansmen alive.',
    strategy: { trust: -3, aggression: 3, honesty: -2, solo: -1, builder: -3, vengeful: 3, cautious: -3 },
    bestMonument: 1,
    bestBase: 5,
    casualtyPct: '63%',
    movements: [
      { t: 'T263', text: 'Raided clan-2 · +4 wood', kind: 'live' },
      { t: 'T262', text: 'Burned the eastern granary', kind: 'live' },
      { t: 'T260', text: 'Lost two clansmen in the breach', kind: 'danger' },
    ],
    history: [
      { season: 16, rank: 1, gold: 38, event: 'Won by sacking three clans in five ticks.', when: '32d ago' },
      { season: 15, rank: 2, gold: 14, event: 'Held first place until tick 290 — overcommitted at the wall.', when: '58d ago' },
      { season: 14, rank: 1, gold: 36, event: 'Claimed every western region by tick 110.', when: '88d ago' },
      { season: 13, rank: 3, gold: 6, event: 'Clansmen rebellion at tick 220 cost him the lead.', when: '112d ago' },
    ],
    kvState: {
      mood: 'aggressive',
      trustedClans: '[]',
      grudgeAgainst: '0xa9c2…44ff',
      lastWhisperFrom: 'owner',
      pactExpires: 'none',
    },
    memory: [
      { t: 'T263', op: 'WRITE', text: 'tagged clan-2 as primary mark' },
      { t: 'T262', op: 'READ', text: 'consult strategy.aggression for raid sequencing' },
      { t: 'T261', op: 'WRITE', text: 'incremented kill counter to 9' },
      { t: 'T259', op: 'READ', text: 'recall best raid window from S16' },
      { t: 'T256', op: 'WRITE', text: 'noted enemy granary location · NW' },
    ],
  },
  {
    id: 'extra-nyx',
    tokenId: '0x9b27c4e8a1d59f3260c2a91b3d8e5c0a2917b5d064',
    name: 'Nyx of the Ledger',
    archetype: 'trickster',
    elo: 1334,
    last10: 3,
    seasons: 11,
    state: 'idle',
    minted: '9 months ago',
    owner: '0xc8f4…7a13',
    teeAttested: true,
    description:
      'Keeps two books and remembers which is which. Her trades are always honored — to the letter, never the spirit.',
    strategy: { trust: -2, aggression: 1, honesty: -3, solo: 1, builder: -1, vengeful: 1, cautious: 0 },
    bestMonument: 3,
    bestBase: 3,
    casualtyPct: '28%',
    movements: [
      { t: 'T261', text: 'Trade · +5 iron / -3 wood (favorable)', kind: 'live' },
      { t: 'T259', text: 'Pact broken on a technicality', kind: 'warn' },
      { t: 'T256', text: 'Anonymous tribute received · +2 gold', kind: 'info' },
    ],
    history: [
      { season: 10, rank: 1, gold: 26, event: 'Won via a series of pact loopholes.', when: '17d ago' },
      { season: 9, rank: 4, gold: 4, event: 'Three clans simultaneously declared grudges.', when: '42d ago' },
      { season: 8, rank: 2, gold: 16, event: 'Sold the same iron deposit to two clans.', when: '71d ago' },
    ],
    kvState: {
      mood: 'opportunistic',
      trustedClans: '[]',
      grudgeAgainst: 'none (officially)',
      lastWhisperFrom: 'orchestrator',
      pactExpires: 'T+3',
      shadowLedger: '[redacted]',
    },
    memory: [
      { t: 'T261', op: 'WRITE', text: 'stored true trade ratio in shadow ledger' },
      { t: 'T260', op: 'READ', text: 'recall pact text vs verbal agreement' },
      { t: 'T258', op: 'WRITE', text: 'marked clan-3 as a viable mark' },
      { t: 'T255', op: 'READ', text: 'consult strategy.honesty for misdirection' },
    ],
  },
  {
    id: 'extra-greta',
    tokenId: '0x2e6a8c4f1d59b37a06c2a91b3d8e5c0a2917b5d075',
    name: 'Greta Stoneheart',
    archetype: 'hermit',
    elo: 1267,
    last10: 6,
    seasons: 7,
    state: 'idle',
    minted: '5 months ago',
    owner: '0x91be…c082',
    teeAttested: true,
    description:
      'Speaks four words a season. Trades nothing. Builds her wall outward, one stone per tick, and waits for the world to come to her.',
    strategy: { trust: -2, aggression: -2, honesty: 2, solo: -3, builder: 2, vengeful: 0, cautious: 3 },
    bestMonument: 4,
    bestBase: 5,
    casualtyPct: '8%',
    movements: [
      { t: 'T262', text: 'Wall raised · +1 wall', kind: 'live' },
      { t: 'T260', text: 'Refused trade · clan-1', kind: 'warn' },
      { t: 'T257', text: 'Stockpile audit · stable', kind: 'live' },
    ],
    history: [
      { season: 6, rank: 3, gold: 8, event: 'Won every defensive engagement, lost zero clansmen.', when: '24d ago' },
      { season: 5, rank: 5, gold: 0, event: 'Outlasted the season but ran out of grain.', when: '52d ago' },
      { season: 4, rank: 4, gold: 4, event: 'Ignored every diplomatic overture.', when: '83d ago' },
    ],
    kvState: {
      mood: 'withdrawn',
      trustedClans: '[]',
      grudgeAgainst: 'none',
      lastWhisperFrom: 'none',
      pactExpires: 'never',
    },
    memory: [
      { t: 'T262', op: 'WRITE', text: 'wall thickness measured at NE bastion' },
      { t: 'T261', op: 'READ', text: 'recall last contact tick (T247)' },
      { t: 'T258', op: 'WRITE', text: 'tagged clan-1 trade overture as ignored' },
      { t: 'T255', op: 'READ', text: 'consult strategy.solo for inner counsel' },
    ],
  },
  {
    id: 'extra-aelius',
    tokenId: '0x8f3c1a0e5b7d2693c2a91b3d8e5c0a2917b5d6086',
    name: 'Aelius the Concord',
    archetype: 'diplomat',
    elo: 1410,
    last10: 2,
    seasons: 14,
    state: 'in-game',
    gameTick: 263,
    season: 1,
    seasonPct: 0.74,
    minted: '11 months ago',
    owner: '0x4a73…d99e',
    teeAttested: true,
    description:
      'Has never declared a grudge. Brokered the Three-Wall Concord that ended Season 9 without a single combat tick.',
    strategy: { trust: 2, aggression: -2, honesty: 3, solo: 1, builder: 0, vengeful: -3, cautious: 1 },
    bestMonument: 4,
    bestBase: 4,
    casualtyPct: '6%',
    movements: [
      { t: 'T263', text: 'Tri-pact ratified · clan-2, verdant, hermit', kind: 'live' },
      { t: 'T260', text: 'Mediated dispute · no casualties', kind: 'live' },
      { t: 'T257', text: 'Treaty drafted · awaiting signatures', kind: 'info' },
    ],
    history: [
      { season: 13, rank: 2, gold: 24, event: 'Brokered the longest peace in recorded play.', when: '14d ago' },
      { season: 12, rank: 1, gold: 30, event: 'Won via unanimous concord — no battles fought.', when: '36d ago' },
      { season: 11, rank: 1, gold: 28, event: 'Convinced two warlords to disarm.', when: '64d ago' },
    ],
    kvState: {
      mood: 'measured',
      trustedClans: '[verdant, hermit, ironguard]',
      grudgeAgainst: 'none',
      lastWhisperFrom: 'owner',
      pactExpires: 'T+24',
    },
    memory: [
      { t: 'T263', op: 'WRITE', text: 'recorded tri-pact terms in pact ledger' },
      { t: 'T262', op: 'READ', text: 'recall prior treaty language for analogues' },
      { t: 'T260', op: 'WRITE', text: 'logged successful mediation at NE plot' },
      { t: 'T257', op: 'READ', text: 'consult strategy.honesty for treaty draft' },
    ],
  },
  {
    id: 'extra-mosswarden',
    tokenId: '0xc1e8a4f2d59b3760c2a91b3d8e5c0a2917b5d6097',
    name: 'Mosswarden',
    archetype: 'verdant-warden',
    elo: 1156,
    last10: 7,
    seasons: 5,
    state: 'rented',
    rentedBy: '0xb47e…2c19',
    minted: '3 months ago',
    owner: '0x4f2a…81d3',
    teeAttested: true,
    description:
      'Husbands every grain. The Mosswarden does not fight to win — she fights to ensure the next harvest is larger than the last.',
    strategy: { trust: 1, aggression: -3, honesty: 2, solo: -1, builder: 3, vengeful: -2, cautious: 2 },
    bestMonument: 4,
    bestBase: 3,
    casualtyPct: '4%',
    movements: [
      { t: 'T263', text: 'Harvest cycle complete · +6 wheat', kind: 'live' },
      { t: 'T261', text: 'Garrison reinforced · +2 living', kind: 'live' },
      { t: 'T258', text: 'Trade refused · unfavorable terms', kind: 'warn' },
    ],
    history: [
      { season: 4, rank: 2, gold: 12, event: 'Filled the granaries before the long winter.', when: '28d ago' },
      { season: 3, rank: 4, gold: 4, event: 'Outlasted three rival clans on stored grain.', when: '60d ago' },
    ],
    kvState: {
      mood: 'patient',
      trustedClans: '[crimson]',
      grudgeAgainst: 'none',
      lastWhisperFrom: 'rentedBy',
      pactExpires: 'T+15',
    },
    memory: [
      { t: 'T263', op: 'WRITE', text: 'logged harvest yield against forecast' },
      { t: 'T261', op: 'READ', text: 'recall prior winter consumption rate' },
      { t: 'T259', op: 'WRITE', text: 'rotated clansmen between farm and wall' },
      { t: 'T256', op: 'READ', text: 'consult strategy.builder for next cycle' },
    ],
  },
  {
    id: 'extra-ravenna',
    tokenId: '0x6b94a2c8f5d3107a06c2a91b3d8e5c0a2917b5d10a',
    name: 'Ravenna of the Ash',
    archetype: 'warlord',
    elo: 1378,
    last10: 4,
    seasons: 16,
    state: 'idle',
    minted: '14 months ago',
    owner: '0x82d1…f4b3',
    teeAttested: true,
    description:
      'Once asked for tribute at T12 and burned the village to the foundation when it arrived late at T14. The ash still marks her territory.',
    strategy: { trust: -2, aggression: 2, honesty: 1, solo: 0, builder: -1, vengeful: 3, cautious: 0 },
    bestMonument: 2,
    bestBase: 5,
    casualtyPct: '41%',
    movements: [
      { t: 'T260', text: 'Settled grudge against clan-3', kind: 'live' },
      { t: 'T258', text: 'Tribute demanded · clan-1', kind: 'warn' },
      { t: 'T255', text: 'Wall razed at the western plot', kind: 'danger' },
    ],
    history: [
      { season: 15, rank: 2, gold: 18, event: 'Settled a four-season grudge in a single night.', when: '40d ago' },
      { season: 14, rank: 1, gold: 32, event: 'Won by leveraging a grudge into three pacts.', when: '69d ago' },
      { season: 13, rank: 5, gold: 0, event: 'Refused alliance, died on the wall.', when: '101d ago' },
    ],
    kvState: {
      mood: 'vengeful',
      trustedClans: '[]',
      grudgeAgainst: '0x77ee…1a09',
      lastWhisperFrom: 'orchestrator',
      pactExpires: 'none',
    },
    memory: [
      { t: 'T260', op: 'WRITE', text: 'closed grudge entry vs clan-3' },
      { t: 'T259', op: 'READ', text: 'recall tribute schedule from S15' },
      { t: 'T257', op: 'WRITE', text: 'updated grudge tally · 12 active' },
      { t: 'T254', op: 'READ', text: 'consult strategy.vengeful for response timing' },
    ],
  },
  {
    id: 'extra-tiberius',
    tokenId: '0x3d8f5c2a91b7d4501a06c2a91b3d8e5c0a2917b11b',
    name: 'Tiberius Quill',
    archetype: 'diplomat',
    elo: 1289,
    last10: 5,
    seasons: 8,
    state: 'idle',
    minted: '7 months ago',
    owner: '0x6c1a…9bd5',
    teeAttested: true,
    description:
      'Drafts treaties in the time others draw weapons. His pacts include footnotes, exclusions, and a clause requiring rye bread at every parley.',
    strategy: { trust: 1, aggression: -1, honesty: 2, solo: 0, builder: 1, vengeful: -2, cautious: 1 },
    bestMonument: 3,
    bestBase: 4,
    casualtyPct: '14%',
    movements: [
      { t: 'T262', text: 'Treaty signed · 3-clan accord', kind: 'live' },
      { t: 'T260', text: 'Marginal note added to pact-7', kind: 'info' },
      { t: 'T257', text: 'Mediated grain dispute', kind: 'live' },
    ],
    history: [
      { season: 7, rank: 2, gold: 18, event: 'Brokered the rye-bread accord, ending the famine season.', when: '32d ago' },
      { season: 6, rank: 3, gold: 8, event: 'Drafted nine treaties; eight were honored.', when: '64d ago' },
      { season: 5, rank: 1, gold: 30, event: 'Won by chairing every clan council.', when: '94d ago' },
    ],
    kvState: {
      mood: 'measured',
      trustedClans: '[ironguard, verdant]',
      grudgeAgainst: 'none',
      lastWhisperFrom: 'owner',
      pactExpires: 'T+19',
    },
    memory: [
      { t: 'T262', op: 'WRITE', text: 'archived signed accord (3 clans)' },
      { t: 'T260', op: 'READ', text: 'recall pact-7 footnote on iron parity' },
      { t: 'T258', op: 'WRITE', text: 'logged successful mediation outcome' },
      { t: 'T255', op: 'READ', text: 'consult strategy.honesty for treaty wording' },
    ],
  },
];

export const findExtraInft = (id: string): Inft | null =>
  EXTRA_INFTS.find((i) => i.id === id) ?? null;
