import fs from 'node:fs';
import {
  createPublicClient,
  createWalletClient,
  http,
  fallback,
  defineChain,
} from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import type { ClanFullView, ClanOrder, Tick } from '../types';
import { readEnv } from './_env';

export interface SubmitOrderResult {
  clansmanId: number;
  status: number;
  cooldownEndsAtTs: string;
  missionNonce: string;
  marketMode: number;
}

export interface SubmitOrdersResult {
  txHash: string;
  results: SubmitOrderResult[];
}

export function uintValue(value: unknown): bigint {
  if (typeof value === 'bigint') {
    return value;
  }

  if (typeof value === 'number') {
    if (!Number.isInteger(value)) {
      throw new Error(`uintValue: non-integer number ${value}`);
    }
    if (!Number.isSafeInteger(value)) {
      throw new Error(`uintValue: unsafe integer number ${value}`);
    }
    if (value < 0) {
      throw new Error(`uintValue: negative number ${value}`);
    }
    return BigInt(value);
  }

  if (typeof value === 'string') {
    if (!/^\d+$/.test(value)) {
      throw new Error(`uintValue: not a non-negative integer string: ${value}`);
    }
    return BigInt(value);
  }

  throw new Error(`uintValue: unsupported type ${typeof value}`);
}

export interface IChainClient {
  getCurrentTick(): Promise<Tick>;
  submitOrders(clanId: string, orders: ClanOrder[]): Promise<SubmitOrdersResult>;
  getClanFullView(clanId: string): Promise<ClanFullView>;
  getWallUpgradeCost(currentLevel: number): Promise<{ wood: bigint; iron: bigint }>;
  getBaseUpgradeCost(currentLevel: number): Promise<{ wood: bigint; iron: bigint; wheat: bigint }>;
  getMonumentUpgradeCost(currentLevel: number): Promise<{ wood: bigint; iron: bigint; wheat: bigint; blueprint: bigint }>;
  getClanScore(clanId: string): Promise<{ score: bigint; monumentReachedAtTick: bigint; monumentLevel: number }>;
  getRankings(): Promise<{ clanIdsRanked: readonly number[]; scores: readonly bigint[] }>;
}

const DEFAULT_CONTRACT_ADDRESS =
  '0x1BF5649f29CbB53E117a5aE969A18A71790f83E8' as const;

export const baseSepolia = defineChain({
  id: 84532,
  name: 'Base Sepolia',
  nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  rpcUrls: {
    default: { http: ['https://sepolia.base.org'] },
  },
});

// BEGIN GENERATED CLAN_WORLD_ABI
// Generated by scripts/gen-chainclient-abi.mjs from packages/contracts/abi/IClanWorld.json.
// Run `pnpm gen:chainclient-abi` after updating the canonical contract ABI.
export const CLAN_WORLD_ABI = [
  {
    "type": "function",
    "name": "heartbeat",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getWorldState",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct WorldState",
        "components": [
          {
            "name": "currentTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "seasonStartTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "seasonEndTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "seasonFinalized",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "currentSeasonNumber",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "nextHeartbeatAtTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "nextHeartbeatAtTs",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "nextBanditSpawnEligibleTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "currentBanditSpawnChanceBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "currentTickSeed",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "activeBanditId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "winterActive",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "winterStartsAtTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "winterEndsAtTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "nextCommitSequence",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getClan",
    "inputs": [
      {
        "name": "clanId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Clan",
        "components": [
          {
            "name": "clanId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "iftTokenId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "owner",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "clanState",
            "type": "uint8",
            "internalType": "enum ClanState"
          },
          {
            "name": "baseRegion",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "baseLevel",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "wallLevel",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "monumentLevel",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "livingClansmen",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "lastSettledTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "starvationStartsAtTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "coldDamage",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "ownerNonce",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "goldBalance",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "blueprintBalance",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "vaultWood",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "vaultIron",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "vaultWheat",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "vaultFish",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getClansman",
    "inputs": [
      {
        "name": "clansmanId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Clansman",
        "components": [
          {
            "name": "clansmanId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "clanId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "state",
            "type": "uint8",
            "internalType": "enum ClansmanState"
          },
          {
            "name": "currentRegion",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "cooldownEndsAtTs",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "lastMissionNonce",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "carryWood",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "carryIron",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "carryWheat",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "carryFish",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getActiveMission",
    "inputs": [
      {
        "name": "clansmanId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct Mission",
        "components": [
          {
            "name": "active",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "nonce",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "submittedAtTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "executesAtTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "settlesAtTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "clansmanId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "startRegion",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "targetRegion",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "action",
            "type": "uint8",
            "internalType": "enum ActionType"
          },
          {
            "name": "startTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "arrivalTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "actionStartTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "missionSeed",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "marketMode",
            "type": "uint8",
            "internalType": "enum MarketExecutionMode"
          },
          {
            "name": "targetClanId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "marketToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "marketAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxGoldIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "withdrawResources",
            "type": "tuple",
            "internalType": "struct WithdrawResourcesData",
            "components": [
              {
                "name": "wood",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "iron",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "wheat",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "fish",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getBanditTroop",
    "inputs": [
      {
        "name": "banditId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct BanditTroop",
        "components": [
          {
            "name": "id",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "region",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "state",
            "type": "uint8",
            "internalType": "enum BanditState"
          },
          {
            "name": "targetClanId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "tickEnteredState",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "strength",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "tier",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "attackAttemptsMade",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "carryWood",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "carryIron",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "carryWheat",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "carryFish",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "carryGold",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getScheduledMarketActionsForTick",
    "inputs": [
      {
        "name": "tick",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple[]",
        "internalType": "struct ScheduledMarketAction[]",
        "components": [
          {
            "name": "executeAtTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "commitSequence",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "missionNonce",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "clanId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "clansmanId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "action",
            "type": "uint8",
            "internalType": "enum ActionType"
          },
          {
            "name": "marketToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "marketAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxGoldIn",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getDerivedClanState",
    "inputs": [
      {
        "name": "clanId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct DerivedClanState",
        "components": [
          {
            "name": "clan",
            "type": "tuple",
            "internalType": "struct Clan",
            "components": [
              {
                "name": "clanId",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "iftTokenId",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "owner",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "clanState",
                "type": "uint8",
                "internalType": "enum ClanState"
              },
              {
                "name": "baseRegion",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "baseLevel",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "wallLevel",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "monumentLevel",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "livingClansmen",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "lastSettledTick",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "starvationStartsAtTick",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "coldDamage",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "ownerNonce",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "goldBalance",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "blueprintBalance",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "vaultWood",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "vaultIron",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "vaultWheat",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "vaultFish",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "isStarving",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "lootValue",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "derivedAtTick",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getDerivedClansmanState",
    "inputs": [
      {
        "name": "clansmanId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct DerivedClansmanState",
        "components": [
          {
            "name": "clansman",
            "type": "tuple",
            "internalType": "struct Clansman",
            "components": [
              {
                "name": "clansmanId",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "clanId",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "state",
                "type": "uint8",
                "internalType": "enum ClansmanState"
              },
              {
                "name": "currentRegion",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "cooldownEndsAtTs",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "lastMissionNonce",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "carryWood",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "carryIron",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "carryWheat",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "carryFish",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "activeMission",
            "type": "tuple",
            "internalType": "struct Mission",
            "components": [
              {
                "name": "active",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "nonce",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "submittedAtTick",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "executesAtTick",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "settlesAtTick",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "clansmanId",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "startRegion",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "targetRegion",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "action",
                "type": "uint8",
                "internalType": "enum ActionType"
              },
              {
                "name": "startTick",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "arrivalTick",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "actionStartTick",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "missionSeed",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "marketMode",
                "type": "uint8",
                "internalType": "enum MarketExecutionMode"
              },
              {
                "name": "targetClanId",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "marketToken",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "marketAmount",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxGoldIn",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "withdrawResources",
                "type": "tuple",
                "internalType": "struct WithdrawResourcesData",
                "components": [
                  {
                    "name": "wood",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "iron",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "wheat",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "fish",
                    "type": "uint256",
                    "internalType": "uint256"
                  }
                ]
              }
            ]
          },
          {
            "name": "effectiveRegion",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "derivedAtTick",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getWorldSnapshot",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct WorldSnapshot",
        "components": [
          {
            "name": "currentTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "seasonStartTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "seasonEndTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "seasonFinalized",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "currentSeasonNumber",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "nextHeartbeatAtTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "winterActive",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "winterStartsAtTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "winterEndsAtTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "activeBanditId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "currentTickSeed",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "leaderboard",
            "type": "tuple[]",
            "internalType": "struct LeaderboardEntry[]",
            "components": [
              {
                "name": "clanId",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "owner",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "monumentLevel",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "baseLevel",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "wallLevel",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "livingClansmen",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "state",
                "type": "uint8",
                "internalType": "enum ClanState"
              },
              {
                "name": "lootValue",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getClanFullView",
    "inputs": [
      {
        "name": "clanId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct ClanFullView",
        "components": [
          {
            "name": "clan",
            "type": "tuple",
            "internalType": "struct DerivedClanState",
            "components": [
              {
                "name": "clan",
                "type": "tuple",
                "internalType": "struct Clan",
                "components": [
                  {
                    "name": "clanId",
                    "type": "uint32",
                    "internalType": "uint32"
                  },
                  {
                    "name": "iftTokenId",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "owner",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "clanState",
                    "type": "uint8",
                    "internalType": "enum ClanState"
                  },
                  {
                    "name": "baseRegion",
                    "type": "uint8",
                    "internalType": "uint8"
                  },
                  {
                    "name": "baseLevel",
                    "type": "uint8",
                    "internalType": "uint8"
                  },
                  {
                    "name": "wallLevel",
                    "type": "uint8",
                    "internalType": "uint8"
                  },
                  {
                    "name": "monumentLevel",
                    "type": "uint8",
                    "internalType": "uint8"
                  },
                  {
                    "name": "livingClansmen",
                    "type": "uint8",
                    "internalType": "uint8"
                  },
                  {
                    "name": "lastSettledTick",
                    "type": "uint64",
                    "internalType": "uint64"
                  },
                  {
                    "name": "starvationStartsAtTick",
                    "type": "uint64",
                    "internalType": "uint64"
                  },
                  {
                    "name": "coldDamage",
                    "type": "uint16",
                    "internalType": "uint16"
                  },
                  {
                    "name": "ownerNonce",
                    "type": "uint64",
                    "internalType": "uint64"
                  },
                  {
                    "name": "goldBalance",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "blueprintBalance",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "vaultWood",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "vaultIron",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "vaultWheat",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "vaultFish",
                    "type": "uint256",
                    "internalType": "uint256"
                  }
                ]
              },
              {
                "name": "isStarving",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "lootValue",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "derivedAtTick",
                "type": "uint64",
                "internalType": "uint64"
              }
            ]
          },
          {
            "name": "clansmen",
            "type": "tuple[]",
            "internalType": "struct ClansmanFullView[]",
            "components": [
              {
                "name": "clansman",
                "type": "tuple",
                "internalType": "struct DerivedClansmanState",
                "components": [
                  {
                    "name": "clansman",
                    "type": "tuple",
                    "internalType": "struct Clansman",
                    "components": [
                      {
                        "name": "clansmanId",
                        "type": "uint32",
                        "internalType": "uint32"
                      },
                      {
                        "name": "clanId",
                        "type": "uint32",
                        "internalType": "uint32"
                      },
                      {
                        "name": "state",
                        "type": "uint8",
                        "internalType": "enum ClansmanState"
                      },
                      {
                        "name": "currentRegion",
                        "type": "uint8",
                        "internalType": "uint8"
                      },
                      {
                        "name": "cooldownEndsAtTs",
                        "type": "uint64",
                        "internalType": "uint64"
                      },
                      {
                        "name": "lastMissionNonce",
                        "type": "uint64",
                        "internalType": "uint64"
                      },
                      {
                        "name": "carryWood",
                        "type": "uint256",
                        "internalType": "uint256"
                      },
                      {
                        "name": "carryIron",
                        "type": "uint256",
                        "internalType": "uint256"
                      },
                      {
                        "name": "carryWheat",
                        "type": "uint256",
                        "internalType": "uint256"
                      },
                      {
                        "name": "carryFish",
                        "type": "uint256",
                        "internalType": "uint256"
                      }
                    ]
                  },
                  {
                    "name": "activeMission",
                    "type": "tuple",
                    "internalType": "struct Mission",
                    "components": [
                      {
                        "name": "active",
                        "type": "bool",
                        "internalType": "bool"
                      },
                      {
                        "name": "nonce",
                        "type": "uint64",
                        "internalType": "uint64"
                      },
                      {
                        "name": "submittedAtTick",
                        "type": "uint64",
                        "internalType": "uint64"
                      },
                      {
                        "name": "executesAtTick",
                        "type": "uint64",
                        "internalType": "uint64"
                      },
                      {
                        "name": "settlesAtTick",
                        "type": "uint64",
                        "internalType": "uint64"
                      },
                      {
                        "name": "clansmanId",
                        "type": "uint32",
                        "internalType": "uint32"
                      },
                      {
                        "name": "startRegion",
                        "type": "uint8",
                        "internalType": "uint8"
                      },
                      {
                        "name": "targetRegion",
                        "type": "uint8",
                        "internalType": "uint8"
                      },
                      {
                        "name": "action",
                        "type": "uint8",
                        "internalType": "enum ActionType"
                      },
                      {
                        "name": "startTick",
                        "type": "uint64",
                        "internalType": "uint64"
                      },
                      {
                        "name": "arrivalTick",
                        "type": "uint64",
                        "internalType": "uint64"
                      },
                      {
                        "name": "actionStartTick",
                        "type": "uint64",
                        "internalType": "uint64"
                      },
                      {
                        "name": "missionSeed",
                        "type": "bytes32",
                        "internalType": "bytes32"
                      },
                      {
                        "name": "marketMode",
                        "type": "uint8",
                        "internalType": "enum MarketExecutionMode"
                      },
                      {
                        "name": "targetClanId",
                        "type": "uint32",
                        "internalType": "uint32"
                      },
                      {
                        "name": "marketToken",
                        "type": "address",
                        "internalType": "address"
                      },
                      {
                        "name": "marketAmount",
                        "type": "uint256",
                        "internalType": "uint256"
                      },
                      {
                        "name": "maxGoldIn",
                        "type": "uint256",
                        "internalType": "uint256"
                      },
                      {
                        "name": "withdrawResources",
                        "type": "tuple",
                        "internalType": "struct WithdrawResourcesData",
                        "components": [
                          {
                            "name": "wood",
                            "type": "uint256",
                            "internalType": "uint256"
                          },
                          {
                            "name": "iron",
                            "type": "uint256",
                            "internalType": "uint256"
                          },
                          {
                            "name": "wheat",
                            "type": "uint256",
                            "internalType": "uint256"
                          },
                          {
                            "name": "fish",
                            "type": "uint256",
                            "internalType": "uint256"
                          }
                        ]
                      }
                    ]
                  },
                  {
                    "name": "effectiveRegion",
                    "type": "uint8",
                    "internalType": "uint8"
                  },
                  {
                    "name": "derivedAtTick",
                    "type": "uint64",
                    "internalType": "uint64"
                  }
                ]
              },
              {
                "name": "activeMission",
                "type": "tuple",
                "internalType": "struct Mission",
                "components": [
                  {
                    "name": "active",
                    "type": "bool",
                    "internalType": "bool"
                  },
                  {
                    "name": "nonce",
                    "type": "uint64",
                    "internalType": "uint64"
                  },
                  {
                    "name": "submittedAtTick",
                    "type": "uint64",
                    "internalType": "uint64"
                  },
                  {
                    "name": "executesAtTick",
                    "type": "uint64",
                    "internalType": "uint64"
                  },
                  {
                    "name": "settlesAtTick",
                    "type": "uint64",
                    "internalType": "uint64"
                  },
                  {
                    "name": "clansmanId",
                    "type": "uint32",
                    "internalType": "uint32"
                  },
                  {
                    "name": "startRegion",
                    "type": "uint8",
                    "internalType": "uint8"
                  },
                  {
                    "name": "targetRegion",
                    "type": "uint8",
                    "internalType": "uint8"
                  },
                  {
                    "name": "action",
                    "type": "uint8",
                    "internalType": "enum ActionType"
                  },
                  {
                    "name": "startTick",
                    "type": "uint64",
                    "internalType": "uint64"
                  },
                  {
                    "name": "arrivalTick",
                    "type": "uint64",
                    "internalType": "uint64"
                  },
                  {
                    "name": "actionStartTick",
                    "type": "uint64",
                    "internalType": "uint64"
                  },
                  {
                    "name": "missionSeed",
                    "type": "bytes32",
                    "internalType": "bytes32"
                  },
                  {
                    "name": "marketMode",
                    "type": "uint8",
                    "internalType": "enum MarketExecutionMode"
                  },
                  {
                    "name": "targetClanId",
                    "type": "uint32",
                    "internalType": "uint32"
                  },
                  {
                    "name": "marketToken",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "marketAmount",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "maxGoldIn",
                    "type": "uint256",
                    "internalType": "uint256"
                  },
                  {
                    "name": "withdrawResources",
                    "type": "tuple",
                    "internalType": "struct WithdrawResourcesData",
                    "components": [
                      {
                        "name": "wood",
                        "type": "uint256",
                        "internalType": "uint256"
                      },
                      {
                        "name": "iron",
                        "type": "uint256",
                        "internalType": "uint256"
                      },
                      {
                        "name": "wheat",
                        "type": "uint256",
                        "internalType": "uint256"
                      },
                      {
                        "name": "fish",
                        "type": "uint256",
                        "internalType": "uint256"
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "name": "westPlot",
            "type": "tuple",
            "internalType": "struct WheatPlot",
            "components": [
              {
                "name": "state",
                "type": "uint8",
                "internalType": "enum WheatPlotState"
              },
              {
                "name": "region",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "remainingWheat",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "regrowUntilTick",
                "type": "uint64",
                "internalType": "uint64"
              }
            ]
          },
          {
            "name": "eastPlot",
            "type": "tuple",
            "internalType": "struct WheatPlot",
            "components": [
              {
                "name": "state",
                "type": "uint8",
                "internalType": "enum WheatPlotState"
              },
              {
                "name": "region",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "remainingWheat",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "regrowUntilTick",
                "type": "uint64",
                "internalType": "uint64"
              }
            ]
          },
          {
            "name": "incomingDefenderIds",
            "type": "uint32[]",
            "internalType": "uint32[]"
          },
          {
            "name": "thisClanDefendingBaseId",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMarketState",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct MarketState",
        "components": [
          {
            "name": "wood",
            "type": "tuple",
            "internalType": "struct PoolReserves",
            "components": [
              {
                "name": "resourceToken",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "resourceReserve",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "goldReserve",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "spotPriceGoldPerResource",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "wheat",
            "type": "tuple",
            "internalType": "struct PoolReserves",
            "components": [
              {
                "name": "resourceToken",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "resourceReserve",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "goldReserve",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "spotPriceGoldPerResource",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "fish",
            "type": "tuple",
            "internalType": "struct PoolReserves",
            "components": [
              {
                "name": "resourceToken",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "resourceReserve",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "goldReserve",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "spotPriceGoldPerResource",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "iron",
            "type": "tuple",
            "internalType": "struct PoolReserves",
            "components": [
              {
                "name": "resourceToken",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "resourceReserve",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "goldReserve",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "spotPriceGoldPerResource",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "currentTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "currentTickQueue",
            "type": "tuple[]",
            "internalType": "struct ScheduledMarketAction[]",
            "components": [
              {
                "name": "executeAtTick",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "commitSequence",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "missionNonce",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "clanId",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "clansmanId",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "action",
                "type": "uint8",
                "internalType": "enum ActionType"
              },
              {
                "name": "marketToken",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "marketAmount",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxGoldIn",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "nextTickQueue",
            "type": "tuple[]",
            "internalType": "struct ScheduledMarketAction[]",
            "components": [
              {
                "name": "executeAtTick",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "commitSequence",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "missionNonce",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "clanId",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "clansmanId",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "action",
                "type": "uint8",
                "internalType": "enum ActionType"
              },
              {
                "name": "marketToken",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "marketAmount",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxGoldIn",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getActiveBanditView",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct ActiveBanditView",
        "components": [
          {
            "name": "exists",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "banditId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "state",
            "type": "uint8",
            "internalType": "enum BanditState"
          },
          {
            "name": "currentRegion",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "attackAttemptsMade",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "maxAttemptsRemaining",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "stateEnteredTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "nextActionTick",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "tier",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "attackPower",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "carryWood",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "carryIron",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "carryWheat",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "carryFish",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "projectedTargetClanId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "projectedTargetLootValue",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getWallUpgradeCost",
    "inputs": [
      {
        "name": "currentLevel",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "wood",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "iron",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "getBaseUpgradeCost",
    "inputs": [
      {
        "name": "currentLevel",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "wood",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "iron",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "wheat",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "getMonumentUpgradeCost",
    "inputs": [
      {
        "name": "currentLevel",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "wood",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "iron",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "wheat",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "blueprint",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "getClanScore",
    "inputs": [
      {
        "name": "clanId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "score",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "monumentReachedAtTick",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "monumentLevel",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRankings",
    "inputs": [],
    "outputs": [
      {
        "name": "clanIdsRanked",
        "type": "uint32[]",
        "internalType": "uint32[]"
      },
      {
        "name": "scores",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "submitClanOrders",
    "inputs": [
      {
        "name": "clanId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "orders",
        "type": "tuple[]",
        "internalType": "struct ClanOrder[]",
        "components": [
          {
            "name": "clansmanId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "gotoRegion",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "action",
            "type": "uint8",
            "internalType": "enum ActionType"
          },
          {
            "name": "targetClanId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "marketToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "marketAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxGoldIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "withdrawResources",
            "type": "tuple",
            "internalType": "struct WithdrawResourcesData",
            "components": [
              {
                "name": "wood",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "iron",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "wheat",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "fish",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple[]",
        "internalType": "struct OrderResult[]",
        "components": [
          {
            "name": "clansmanId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum StatusCode"
          },
          {
            "name": "cooldownEndsAtTs",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "missionNonce",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "marketMode",
            "type": "uint8",
            "internalType": "enum MarketExecutionMode"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferGold",
    "inputs": [
      {
        "name": "fromClanId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "toClanId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferVaultResource",
    "inputs": [
      {
        "name": "fromClanId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "toClanId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "resource",
        "type": "uint8",
        "internalType": "enum ResourceType"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferBlueprint",
    "inputs": [
      {
        "name": "fromClanId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "toClanId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferBundle",
    "inputs": [
      {
        "name": "fromClanId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "toClanId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "gold",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "blueprint",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "wood",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "iron",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "wheat",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "fish",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferClanOwnership",
    "inputs": [
      {
        "name": "clanId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "GoldTransferred",
    "inputs": [
      {
        "name": "fromClanId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "toClanId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "atTick",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "VaultResourceTransferred",
    "inputs": [
      {
        "name": "fromClanId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "toClanId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "resource",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum ResourceType"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "atTick",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BlueprintTransferred",
    "inputs": [
      {
        "name": "fromClanId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "toClanId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "atTick",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ClanOwnershipTransferred",
    "inputs": [
      {
        "name": "clanId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "oldOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwnerNonce",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  }
] as const;
// END GENERATED CLAN_WORLD_ABI

/**
 * Parse and validate a clanId string into a uint32-range integer.
 * Throws descriptive errors for negative, non-integer, empty, or overflow inputs.
 */
export function parseClanId(clanId: string, fnName: string): number {
  if (!/^\d+$/.test(clanId.trim())) {
    throw new Error(`${fnName}: clanId must be a non-negative decimal integer, got '${clanId}'`);
  }
  const parsed = Number.parseInt(clanId.trim(), 10);
  if (parsed > 0xFFFFFFFF) {
    throw new Error(`${fnName}: clanId exceeds uint32 max (4294967295), got '${clanId}'`);
  }
  if (parsed === 0) {
    throw new Error(`${fnName}: clanId 0 is reserved (clan IDs start at 1), got '${clanId}'`);
  }
  return parsed;
}

class StubChainClient implements IChainClient {
  async getCurrentTick(): Promise<Tick> {
    return 0;
  }
  async submitOrders(_clanId: string, _orders: ClanOrder[]): Promise<SubmitOrdersResult> {
    return { txHash: '0xstub', results: [] };
  }
  async getClanFullView(clanId: string): Promise<ClanFullView> {
    return {
      clan: { id: clanId, name: `clan-${clanId}`, treasury: '0' },
      controlledRegions: [],
      pendingOrders: [],
      whispers: [],
    };
  }
  async getWallUpgradeCost(_currentLevel: number): Promise<{ wood: bigint; iron: bigint }> {
    return { wood: 0n, iron: 0n };
  }
  async getBaseUpgradeCost(_currentLevel: number): Promise<{ wood: bigint; iron: bigint; wheat: bigint }> {
    return { wood: 0n, iron: 0n, wheat: 0n };
  }
  async getMonumentUpgradeCost(_currentLevel: number): Promise<{ wood: bigint; iron: bigint; wheat: bigint; blueprint: bigint }> {
    return { wood: 0n, iron: 0n, wheat: 0n, blueprint: 0n };
  }
  async getClanScore(_clanId: string): Promise<{ score: bigint; monumentReachedAtTick: bigint; monumentLevel: number }> {
    return { score: 0n, monumentReachedAtTick: 0n, monumentLevel: 0 };
  }
  async getRankings(): Promise<{ clanIdsRanked: readonly number[]; scores: readonly bigint[] }> {
    return { clanIdsRanked: [], scores: [] };
  }
}

class RealChainClient implements IChainClient {
  private readonly client: ReturnType<typeof createPublicClient>;
  private readonly contractAddress: `0x${string}`;
  private readonly transport:
    | ReturnType<typeof http>
    | ReturnType<typeof fallback>;

  constructor() {
    const primaryRpc = readEnv('RPC_URL_PRIMARY');
    const fallbackRpc = readEnv('RPC_URL_FALLBACK');

    this.transport =
      primaryRpc && fallbackRpc
        ? fallback([http(primaryRpc), http(fallbackRpc)])
        : http(primaryRpc ?? fallbackRpc);

    this.contractAddress = (readEnv('CLAN_WORLD_CONTRACT_ADDRESS') ??
      DEFAULT_CONTRACT_ADDRESS) as `0x${string}`;

    this.client = createPublicClient({
      chain: baseSepolia,
      transport: this.transport,
    });
  }

  async getCurrentTick(): Promise<Tick> {
    const snapshot = await this.client.readContract({
      address: this.contractAddress,
      abi: CLAN_WORLD_ABI,
      functionName: 'getWorldSnapshot',
    });
    return Number(snapshot.currentTick); // safe: tick values are small enough to fit Number precisely in Wave 0
  }

  async submitOrders(clanId: string, orders: ClanOrder[]): Promise<SubmitOrdersResult> {
    // Wave 0: single-Elder only — concurrent nonce coordination deferred to Wave 1
    const parsedClanId = parseClanId(clanId, 'submitOrders');

    for (const order of orders) {
      if (order.kind === 'mission') {
        const { clansmanId, gotoRegion, action } = order.payload;
        if (
          clansmanId === undefined ||
          gotoRegion === undefined ||
          action === undefined
        ) {
          throw new Error(
            `submitOrders: mission order missing required payload fields (clansmanId, gotoRegion, action)`,
          );
        }
      }
    }

    const nonMissionOrders = orders.filter((o) => o.kind !== 'mission');
    if (nonMissionOrders.length > 0) {
      console.warn(
        `[RealChainClient] submitOrders: ${nonMissionOrders.length} non-mission order(s) skipped (Wave 0 only supports 'mission' kind)`,
      );
    }

    const contractOrders = orders
      .filter((o) => o.kind === 'mission')
      .map((o) => {
        const withdraw =
          o.payload.withdrawResources &&
          typeof o.payload.withdrawResources === 'object'
            ? (o.payload.withdrawResources as Record<string, unknown>)
            : o.payload;
        const optionalUintValue = (value: unknown): bigint =>
          value === undefined || value === null ? 0n : uintValue(value);
        return {
          clansmanId: Number(o.payload.clansmanId),
          gotoRegion: Number(o.payload.gotoRegion),
          action: Number(o.payload.action),
          targetClanId: 0,
          marketToken:
            '0x0000000000000000000000000000000000000000' as `0x${string}`,
          marketAmount: 0n,
          maxGoldIn: 0n,
          withdrawResources: {
            wood: optionalUintValue(withdraw.wood),
            iron: optionalUintValue(withdraw.iron),
            wheat: optionalUintValue(withdraw.wheat),
            fish: optionalUintValue(withdraw.fish),
          },
        };
      });

    if (contractOrders.length === 0) {
      throw new Error('submitOrders: no valid mission orders to submit');
    }

    const keyPath = readEnv('ELDER_WALLET_KEY_PATH');
    let pk: string | undefined;
    let pkSource: string | undefined;
    if (keyPath) {
      try {
        pk = fs.readFileSync(keyPath, 'utf8').trim();
        pkSource = `ELDER_WALLET_KEY_PATH file at ${keyPath}`;
      } catch (err) {
        if (
          err &&
          typeof err === 'object' &&
          'code' in err &&
          err.code === 'ENOENT'
        ) {
          throw new Error(
            `ELDER_WALLET_KEY_PATH file not found at ${keyPath}; either set DEPLOYER_PRIVATE_KEY env var or provide a key file`,
          );
        }
        const msg = err instanceof Error ? err.message : String(err);
        throw new Error(
          `Failed to read ELDER_WALLET_KEY_PATH file at ${keyPath}: ${msg}`,
        );
      }
    } else {
      const fallbackKey = readEnv('DEPLOYER_PRIVATE_KEY');
      if (fallbackKey) {
        console.warn(
          '[RealChainClient] ELDER_WALLET_KEY_PATH not set; falling back to DEPLOYER_PRIVATE_KEY (deprecated)',
        );
        pk = fallbackKey;
        pkSource = 'DEPLOYER_PRIVATE_KEY env var';
      }
    }
    if (!pk)
      throw new Error(
        'Neither ELDER_WALLET_KEY_PATH nor DEPLOYER_PRIVATE_KEY is set',
      );

    // Normalize: add 0x prefix if missing
    if (!pk.startsWith('0x')) pk = '0x' + pk;
    if (!/^0x[0-9a-fA-F]{64}$/.test(pk)) {
      throw new Error(
        `Invalid private key from ${pkSource ?? 'unknown source'}: expected a 64-hex-char private key (0x-prefixed optional)`,
      );
    }

    const account = privateKeyToAccount(pk as `0x${string}`);
    const simulation = await this.client.simulateContract({
      account,
      address: this.contractAddress,
      abi: CLAN_WORLD_ABI,
      functionName: 'submitClanOrders',
      args: [parsedClanId, contractOrders],
    });

    const results = simulation.result.map(result => ({
      clansmanId: Number(result.clansmanId),
      status: Number(result.status),
      cooldownEndsAtTs: result.cooldownEndsAtTs.toString(),
      missionNonce: result.missionNonce.toString(),
      marketMode: Number(result.marketMode),
    }));

    const walletClient = createWalletClient({
      account,
      chain: baseSepolia,
      transport: this.transport,
    });

    const hash = await walletClient.writeContract(simulation.request);

    return { txHash: hash, results };
  }

  async getClanFullView(clanId: string): Promise<ClanFullView> {
    const result = await this.client.readContract({
      address: this.contractAddress,
      abi: CLAN_WORLD_ABI,
      functionName: 'getClanFullView',
      args: [parseClanId(clanId, 'getClanFullView')],
    });

    const inner = result.clan.clan;
    return {
      clan: {
        id: String(inner.clanId),
        name: `clan-${inner.clanId}`,
        treasury: String(inner.goldBalance),
      },
      // controlledRegions, pendingOrders, whispers not available in Wave 0 contract read
      controlledRegions: [], // Wave 0: omit base region from controlledRegions; populated in Wave 1 from on-chain data
      pendingOrders: [],
      whispers: [],
    };
  }

  async getWallUpgradeCost(currentLevel: number): Promise<{ wood: bigint; iron: bigint }> {
    const [wood, iron] = await this.client.readContract({
      address: this.contractAddress,
      abi: CLAN_WORLD_ABI,
      functionName: 'getWallUpgradeCost',
      args: [currentLevel],
    });
    return { wood, iron };
  }

  async getBaseUpgradeCost(currentLevel: number): Promise<{ wood: bigint; iron: bigint; wheat: bigint }> {
    const [wood, iron, wheat] = await this.client.readContract({
      address: this.contractAddress,
      abi: CLAN_WORLD_ABI,
      functionName: 'getBaseUpgradeCost',
      args: [currentLevel],
    });
    return { wood, iron, wheat };
  }

  async getMonumentUpgradeCost(currentLevel: number): Promise<{ wood: bigint; iron: bigint; wheat: bigint; blueprint: bigint }> {
    const [wood, iron, wheat, blueprint] = await this.client.readContract({
      address: this.contractAddress,
      abi: CLAN_WORLD_ABI,
      functionName: 'getMonumentUpgradeCost',
      args: [currentLevel],
    });
    return { wood, iron, wheat, blueprint };
  }

  async getClanScore(clanId: string): Promise<{ score: bigint; monumentReachedAtTick: bigint; monumentLevel: number }> {
    const [score, monumentReachedAtTick, monumentLevel] = await this.client.readContract({
      address: this.contractAddress,
      abi: CLAN_WORLD_ABI,
      functionName: 'getClanScore',
      args: [parseClanId(clanId, 'getClanScore')],
    });
    return { score, monumentReachedAtTick, monumentLevel };
  }

  async getRankings(): Promise<{ clanIdsRanked: readonly number[]; scores: readonly bigint[] }> {
    const [clanIdsRanked, scores] = await this.client.readContract({
      address: this.contractAddress,
      abi: CLAN_WORLD_ABI,
      functionName: 'getRankings',
    });
    return { clanIdsRanked: clanIdsRanked as readonly number[], scores };
  }
}

export function createChainClient(): IChainClient {
  return readEnv('CLAN_WORLD_USE_STUB_CHAIN') === 'true'
    ? new StubChainClient()
    : new RealChainClient();
}
