#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const sourcePath = path.join(repoRoot, 'packages/contracts/src/IClanWorld.sol');
const targetPath = path.join(repoRoot, 'packages/sdk/src/generated/enums.ts');
const compatTargetPath = path.join(repoRoot, 'packages/shared/src/generated/enums.ts');

const enumNames = [
  'ActionType',
  'StatusCode',
  'ResourceType',
  'ClansmanState',
  'ClanState',
  'BanditState',
  'WheatPlotState',
  'MarketExecutionMode',
];

function stripComments(source) {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\/\/.*$/gm, '');
}

function parseEnums(source) {
  const cleanSource = stripComments(source);
  const enums = new Map();
  const enumPattern = /enum\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{([\s\S]*?)\}/g;
  let match;

  while ((match = enumPattern.exec(cleanSource)) !== null) {
    const [, name, body] = match;
    const values = body
      .split(',')
      .map(value => value.trim())
      .filter(Boolean);
    enums.set(name, values);
  }

  return enums;
}

function renderEnum(name, values) {
  const entries = values.map((value, index) => `  ${value}: ${index},`).join('\n');
  return [
    `export const ${name} = {`,
    entries,
    `} as const;`,
    `export type ${name} = (typeof ${name})[keyof typeof ${name}];`,
  ].join('\n');
}

function render(enums) {
  const missing = enumNames.filter(name => !enums.has(name));
  if (missing.length > 0) {
    throw new Error(`Missing enum(s) in ${path.relative(repoRoot, sourcePath)}: ${missing.join(', ')}`);
  }

  return [
    '// Generated by scripts/gen-enums.mjs - do NOT edit by hand',
    '',
    ...enumNames.map(name => renderEnum(name, enums.get(name))),
    '',
  ].join('\n\n');
}

function renderCompat() {
  return [
    '// Compatibility re-export. Canonical generated enums live in @clan-world/sdk.',
    "export * from '@clan-world/sdk/enums';",
    '',
  ].join('\n');
}

const source = fs.readFileSync(sourcePath, 'utf8');
const output = render(parseEnums(source));
const compatOutput = renderCompat();
const check = process.argv.includes('--check');

if (check) {
  const current = fs.existsSync(targetPath) ? fs.readFileSync(targetPath, 'utf8') : '';
  const currentCompat = fs.existsSync(compatTargetPath) ? fs.readFileSync(compatTargetPath, 'utf8') : '';
  if (current !== output || currentCompat !== compatOutput) {
    console.error('Generated enums are out of date. Run `pnpm gen:enums`.');
    process.exit(1);
  }
  console.log('Generated enums are up to date.');
} else {
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(targetPath, output);
  fs.mkdirSync(path.dirname(compatTargetPath), { recursive: true });
  fs.writeFileSync(compatTargetPath, compatOutput);
  console.log(`Updated ${path.relative(repoRoot, targetPath)} from ${path.relative(repoRoot, sourcePath)}.`);
  console.log(`Updated ${path.relative(repoRoot, compatTargetPath)} compatibility re-export.`);
}
