// SPDX-License-Identifier: MIT
pragma solidity ^0.8.34;

library LibOrderTravel {
    function travelTicks(uint8 fromRegion, uint8 toRegion) public pure returns (uint8) {
        if (fromRegion == 0 || toRegion == 0 || fromRegion == toRegion || fromRegion > 8 || toRegion > 8) return 0;
        uint8[64] memory d = [
            0,
            1,
            2,
            1,
            3,
            2,
            4,
            3,
            1,
            0,
            1,
            2,
            2,
            3,
            3,
            4,
            2,
            1,
            0,
            1,
            1,
            2,
            2,
            3,
            1,
            2,
            1,
            0,
            2,
            1,
            3,
            2,
            3,
            2,
            1,
            2,
            0,
            3,
            1,
            2,
            2,
            3,
            2,
            1,
            3,
            0,
            2,
            1,
            4,
            3,
            2,
            3,
            1,
            2,
            0,
            1,
            3,
            4,
            3,
            2,
            2,
            1,
            1,
            0
        ];
        return d[uint8(fromRegion - 1) * 8 + uint8(toRegion - 1)];
    }
}
